name: CI build

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  build-core-and-single:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JVM_version: ['21', '25']
    if: ${{ github.repository_owner == 'cryostatio' }}
    steps:
    - name: Fail if PR and safe-to-test label NOT applied
      if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'safe-to-test') }}
      run: exit 1
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: ${{ matrix.JVM_version }}
        distribution: 'temurin'
    - uses: skjolber/maven-cache-github-action@358c6249a8435d41794af43a2de43d935e2c9a3c # v1
      with:
        step: restore
    - run: ./mvnw -B -U clean verify -pl cryostat-mcp-core,cryostat-mcp-single -am
    - uses: skjolber/maven-cache-github-action@358c6249a8435d41794af43a2de43d935e2c9a3c # v1
      with:
        step: save

  build-k8s-mux:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'cryostatio' }}
    steps:
    - name: Fail if PR and safe-to-test label NOT applied
      if: ${{ github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'safe-to-test') }}
      run: exit 1
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        java-version: '25'
        distribution: 'temurin'
    - uses: skjolber/maven-cache-github-action@358c6249a8435d41794af43a2de43d935e2c9a3c # v1
      with:
        step: restore
    - run: ./mvnw -B -U clean verify -pl cryostat-mcp-k8s-mux -am
    - uses: skjolber/maven-cache-github-action@358c6249a8435d41794af43a2de43d935e2c9a3c # v1
      with:
        step: save

